AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  UseCache: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '^\s*#'

Metrics/BlockLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/routes.rb'
    - 'test/**/*'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/**/*'
    - 'test/**/*'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/controllers/users/registrations_controller.rb'
    - 'app/controllers/users/sessions_controller.rb'
    - 'test/**/*'

Metrics/ParameterLists:
  Exclude:
    - 'test/support/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/**/*'

Style/OneClassPerFile:
  Exclude:
    - 'test/test_helper.rb'
